// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 05/25/2020 23:03:05+0200.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.ub.ehealth.dhislink.redacap.auth;

import bw.ub.ehealth.dhislink.redacap.auth.vo.RedcapAuthLocationVO;
import org.springframework.stereotype.Repository;

/**
 * @see RedcapAuthLocation
 */
@Repository("redcapAuthLocationDao")
public class RedcapAuthLocationDaoImpl
    extends RedcapAuthLocationDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    public void toRedcapAuthLocationVO(
        RedcapAuthLocation source,
        RedcapAuthLocationVO target)
    {
        // TODO verify behavior of toRedcapAuthLocationVO
        super.toRedcapAuthLocationVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedcapAuthLocationVO toRedcapAuthLocationVO(final RedcapAuthLocation entity)
    {
        // TODO verify behavior of toRedcapAuthLocationVO
        return super.toRedcapAuthLocationVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private RedcapAuthLocation loadRedcapAuthLocationFromRedcapAuthLocationVO(RedcapAuthLocationVO redcapAuthLocationVO)
    {
        // TODO implement loadRedcapAuthLocationFromRedcapAuthLocationVO
        throw new UnsupportedOperationException("bw.ub.ehealth.dhislink.redacap.auth.loadRedcapAuthLocationFromRedcapAuthLocationVO(RedcapAuthLocationVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (redcapAuthLocationVO.getId() == null)
        {
            return  RedcapAuthLocation.Factory.newInstance();
        }
        else
        {
            return this.load(redcapAuthLocationVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public RedcapAuthLocation redcapAuthLocationVOToEntity(RedcapAuthLocationVO redcapAuthLocationVO)
    {
        // TODO verify behavior of redcapAuthLocationVOToEntity
        RedcapAuthLocation entity = this.loadRedcapAuthLocationFromRedcapAuthLocationVO(redcapAuthLocationVO);
        this.redcapAuthLocationVOToEntity(redcapAuthLocationVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void redcapAuthLocationVOToEntity(
        RedcapAuthLocationVO source,
        RedcapAuthLocation target,
        boolean copyIfNull)
    {
        // TODO verify behavior of redcapAuthLocationVOToEntity
        super.redcapAuthLocationVOToEntity(source, target, copyIfNull);
    }
}