// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 * Generated by hibernate/HibernateEntityImpl.vsl in andromda-hibernate-cartridge on 05/25/2020 23:03:08+0200.
 */
package bw.ub.ehealth.dhislink.redacap.auth;

import java.util.Collection;

/**
 * @see RedcapAuthLocation
 */
// HibernateEntityImpl.vsl annotations merge-point
public class RedcapAuthLocationImpl
    extends RedcapAuthLocation
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5537479423037070268L;

    /**
     * @see RedcapAuthLocation#findAuthLocation(Long)
     */
    @Override
    public RedcapAuthLocation findAuthLocation(Long authId)
    {
        // TODO implement public RedcapAuthLocation findAuthLocation(Long authId)
        RedcapAuthLocation rtn = null;
        return rtn;
    }

    /**
     * @see RedcapAuthLocation#findLocationAuths(Long)
     */
    @Override
    public Collection<RedcapAuth> findLocationAuths(Long locationId)
    {
        // TODO implement public Collection<RedcapAuth> findLocationAuths(Long locationId)
        Collection<RedcapAuth> rtn = null;
        return rtn;
    }

// HibernateEntityImpl.vsl merge-point
}