// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 05/30/2020 22:17:15+0200.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.ub.ehealth.dhislink.user;

import javax.persistence.NoResultException;
import javax.persistence.NonUniqueResultException;
import javax.persistence.Query;
import javax.validation.constraints.NotNull;

import org.springframework.stereotype.Repository;

/**
 * @see bw.ub.ehealth.dhislink.user.UserRight
 */
@Repository("userRightDao")
public class UserRightDaoImpl
    extends UserRightDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    protected String handleGetUserProjectToken(@NotNull String username, @NotNull Long projectId)
    {
    	String queryStr = "select r from UserRight r where username = :username and projectId = :projectId";
    	Query query = entityManager.createQuery(queryStr);
    	query.setParameter("username", username);
    	query.setParameter("projectId", projectId);
    	
    	try {
			UserRight right = (UserRight) query.getSingleResult();
			return right.getApiToken();
		} catch(NoResultException | NonUniqueResultException e) {
			return null;
		}
    }

}