package bw.ub.ehealth.controller;

import java.util.ArrayList;

public class RedcapUtils {
	public static String[] extractionBarcodeFields = new String[] { "test_ext_barcode_1", "test_ext_barcode_2",
			"test_ext_barcode_3", "test_ext_barcode_4", "test_ext_barcode_5", "test_ext_barcode_6",
			"test_ext_barcode_7", "test_ext_barcode_8", "test_ext_barcode_9", "test_ext_barcode_10",
			"test_ext_barcode_11", "test_ext_barcode_12", "test_ext_barcode_13", "test_ext_barcode_14",
			"test_ext_barcode_15", "test_ext_barcode_16", "test_ext_barcode_17", "test_ext_barcode_18",
			"test_ext_barcode_19", "test_ext_barcode_20", "test_ext_barcode_21", "test_ext_barcode_22",
			"test_ext_barcode_23", "test_ext_barcode_24", "test_ext_barcode_25", "test_ext_barcode_26",
			"test_ext_barcode_27", "test_ext_barcode_28", "test_ext_barcode_29", "test_ext_barcode_30",
			"test_ext_barcode_31", "test_ext_barcode_32", "test_ext_barcode_33", "test_ext_barcode_34",
			"test_ext_barcode_35", "test_ext_barcode_36", "test_ext_barcode_37", "test_ext_barcode_38",
			"test_ext_barcode_39", "test_ext_barcode_40", "test_ext_barcode_41", "test_ext_barcode_42",
			"test_ext_barcode_43", "test_ext_barcode_44", "test_ext_barcode_45", "test_ext_barcode_46",
			"test_ext_barcode_47", "test_ext_barcode_48", "test_ext_barcode_49", "test_ext_barcode_50",
			"test_ext_barcode_51", "test_ext_barcode_52", "test_ext_barcode_53", "test_ext_barcode_54",
			"test_ext_barcode_55", "test_ext_barcode_56", "test_ext_barcode_57", "test_ext_barcode_58",
			"test_ext_barcode_59", "test_ext_barcode_60", "test_ext_barcode_61", "test_ext_barcode_62",
			"test_ext_barcode_63", "test_ext_barcode_64", "test_ext_barcode_65", "test_ext_barcode_66",
			"test_ext_barcode_67", "test_ext_barcode_68", "test_ext_barcode_69", "test_ext_barcode_70",
			"test_ext_barcode_71", "test_ext_barcode_72", "test_ext_barcode_73", "test_ext_barcode_74",
			"test_ext_barcode_75", "test_ext_barcode_76", "test_ext_barcode_77", "test_ext_barcode_78",
			"test_ext_barcode_79", "test_ext_barcode_80", "test_ext_barcode_81", "test_ext_barcode_82",
			"test_ext_barcode_83", "test_ext_barcode_84", "test_ext_barcode_85", "test_ext_barcode_86",
			"test_ext_barcode_87", "test_ext_barcode_88", "test_ext_barcode_89", "test_ext_barcode_90",
			"test_ext_barcode_91", "test_ext_barcode_92", "test_ext_barcode_93", "test_ext_barcode_94",
			"test_ext_barcode_95", "test_ext_barcode_96" };

	public static String[] receptionBarcodeFields = new String[] { "lab_rec_barcode_1", "lab_rec_barcode_2",
			"lab_rec_barcode_3", "lab_rec_barcode_4", "lab_rec_barcode_5", "lab_rec_barcode_6", "lab_rec_barcode_7",
			"lab_rec_barcode_8", "lab_rec_barcode_9", "lab_rec_barcode_10", "lab_rec_barcode_11", "lab_rec_barcode_12",
			"lab_rec_barcode_13", "lab_rec_barcode_14", "lab_rec_barcode_15", "lab_rec_barcode_16",
			"lab_rec_barcode_17", "lab_rec_barcode_18", "lab_rec_barcode_19", "lab_rec_barcode_20",
			"lab_rec_barcode_21", "lab_rec_barcode_22", "lab_rec_barcode_23", "lab_rec_barcode_24",
			"lab_rec_barcode_25", "lab_rec_barcode_26", "lab_rec_barcode_27", "lab_rec_barcode_28",
			"lab_rec_barcode_29", "lab_rec_barcode_30", "lab_rec_barcode_31", "lab_rec_barcode_32",
			"lab_rec_barcode_33", "lab_rec_barcode_34", "lab_rec_barcode_35", "lab_rec_barcode_36",
			"lab_rec_barcode_37", "lab_rec_barcode_38", "lab_rec_barcode_39", "lab_rec_barcode_40",
			"lab_rec_barcode_41", "lab_rec_barcode_42", "lab_rec_barcode_43", "lab_rec_barcode_44",
			"lab_rec_barcode_45", "lab_rec_barcode_46", "lab_rec_barcode_47", "lab_rec_barcode_48",
			"lab_rec_barcode_49", "lab_rec_barcode_50", "lab_rec_barcode_51", "lab_rec_barcode_52",
			"lab_rec_barcode_53", "lab_rec_barcode_54", "lab_rec_barcode_55", "lab_rec_barcode_56",
			"lab_rec_barcode_57", "lab_rec_barcode_58", "lab_rec_barcode_59", "lab_rec_barcode_60",
			"lab_rec_barcode_61", "lab_rec_barcode_62", "lab_rec_barcode_63", "lab_rec_barcode_64",
			"lab_rec_barcode_65", "lab_rec_barcode_66", "lab_rec_barcode_67", "lab_rec_barcode_68",
			"lab_rec_barcode_69", "lab_rec_barcode_70", "lab_rec_barcode_71", "lab_rec_barcode_72",
			"lab_rec_barcode_73", "lab_rec_barcode_74", "lab_rec_barcode_75", "lab_rec_barcode_76",
			"lab_rec_barcode_77", "lab_rec_barcode_78", "lab_rec_barcode_79", "lab_rec_barcode_80",
			"lab_rec_barcode_81", "lab_rec_barcode_82", "lab_rec_barcode_83", "lab_rec_barcode_84",
			"lab_rec_barcode_85", "lab_rec_barcode_86", "lab_rec_barcode_87", "lab_rec_barcode_88",
			"lab_rec_barcode_89", "lab_rec_barcode_90", "lab_rec_barcode_91", "lab_rec_barcode_92",
			"lab_rec_barcode_93", "lab_rec_barcode_94", "lab_rec_barcode_95", "lab_rec_barcode_96" };

	public static String[] tporBarcodeFields = new String[] { "lab_tpor_barcode_1", "lab_tpor_barcode_2",
			"lab_tpor_barcode_3", "lab_tpor_barcode_4", "lab_tpor_barcode_5", "lab_tpor_barcode_6",
			"lab_tpor_barcode_7", "lab_tpor_barcode_8", "lab_tpor_barcode_9", "lab_tpor_barcode_10",
			"lab_tpor_barcode_11", "lab_tpor_barcode_12", "lab_tpor_barcode_13", "lab_tpor_barcode_14",
			"lab_tpor_barcode_15", "lab_tpor_barcode_16", "lab_tpor_barcode_17", "lab_tpor_barcode_18",
			"lab_tpor_barcode_19", "lab_tpor_barcode_20", "lab_tpor_barcode_21", "lab_tpor_barcode_22",
			"lab_tpor_barcode_23", "lab_tpor_barcode_24", "lab_tpor_barcode_25", "lab_tpor_barcode_26",
			"lab_tpor_barcode_27", "lab_tpor_barcode_28", "lab_tpor_barcode_29", "lab_tpor_barcode_30",
			"lab_tpor_barcode_31", "lab_tpor_barcode_32", "lab_tpor_barcode_33", "lab_tpor_barcode_34",
			"lab_tpor_barcode_35", "lab_tpor_barcode_36", "lab_tpor_barcode_37", "lab_tpor_barcode_38",
			"lab_tpor_barcode_39", "lab_tpor_barcode_40", "lab_tpor_barcode_41", "lab_tpor_barcode_42",
			"lab_tpor_barcode_43", "lab_tpor_barcode_44", "lab_tpor_barcode_45", "lab_tpor_barcode_46",
			"lab_tpor_barcode_47", "lab_tpor_barcode_48", "lab_tpor_barcode_49", "lab_tpor_barcode_50",
			"lab_tpor_barcode_51", "lab_tpor_barcode_52", "lab_tpor_barcode_53", "lab_tpor_barcode_54",
			"lab_tpor_barcode_55", "lab_tpor_barcode_56", "lab_tpor_barcode_57", "lab_tpor_barcode_58",
			"lab_tpor_barcode_59", "lab_tpor_barcode_60", "lab_tpor_barcode_61", "lab_tpor_barcode_62",
			"lab_tpor_barcode_63", "lab_tpor_barcode_64", "lab_tpor_barcode_65", "lab_tpor_barcode_66",
			"lab_tpor_barcode_67", "lab_tpor_barcode_68", "lab_tpor_barcode_69", "lab_tpor_barcode_70",
			"lab_tpor_barcode_71", "lab_tpor_barcode_72", "lab_tpor_barcode_73", "lab_tpor_barcode_74",
			"lab_tpor_barcode_75", "lab_tpor_barcode_76", "lab_tpor_barcode_77", "lab_tpor_barcode_78",
			"lab_tpor_barcode_79", "lab_tpor_barcode_80", "lab_tpor_barcode_81", "lab_tpor_barcode_82",
			"lab_tpor_barcode_83", "lab_tpor_barcode_84", "lab_tpor_barcode_85", "lab_tpor_barcode_86",
			"lab_tpor_barcode_87", "lab_tpor_barcode_88", "lab_tpor_barcode_89", "lab_tpor_barcode_90",
			"lab_tpor_barcode_91", "lab_tpor_barcode_92", "lab_tpor_barcode_93", "lab_tpor_barcode_94",
			"lab_tpor_barcode_95", "lab_tpor_barcode_96" };

	public static String[] detectionBarcodeFields = new String[] { "test_det_barcode_1", "test_det_barcode_2",
			"test_det_barcode_3", "test_det_barcode_4", "test_det_barcode_5", "test_det_barcode_6",
			"test_det_barcode_7", "test_det_barcode_8", "test_det_barcode_9", "test_det_barcode_10",
			"test_det_barcode_11", "test_det_barcode_12", "test_det_barcode_13", "test_det_barcode_14",
			"test_det_barcode_15", "test_det_barcode_16", "test_det_barcode_17", "test_det_barcode_18",
			"test_det_barcode_19", "test_det_barcode_20", "test_det_barcode_21", "test_det_barcode_22",
			"test_det_barcode_23", "test_det_barcode_24", "test_det_barcode_25", "test_det_barcode_26",
			"test_det_barcode_27", "test_det_barcode_28", "test_det_barcode_29", "test_det_barcode_30",
			"test_det_barcode_31", "test_det_barcode_32", "test_det_barcode_33", "test_det_barcode_34",
			"test_det_barcode_35", "test_det_barcode_36", "test_det_barcode_37", "test_det_barcode_38",
			"test_det_barcode_39", "test_det_barcode_40", "test_det_barcode_41", "test_det_barcode_42",
			"test_det_barcode_43", "test_det_barcode_44", "test_det_barcode_45", "test_det_barcode_46",
			"test_det_barcode_47", "test_det_barcode_48", "test_det_barcode_49", "test_det_barcode_50",
			"test_det_barcode_51", "test_det_barcode_52", "test_det_barcode_53", "test_det_barcode_54",
			"test_det_barcode_55", "test_det_barcode_56", "test_det_barcode_57", "test_det_barcode_58",
			"test_det_barcode_59", "test_det_barcode_60", "test_det_barcode_61", "test_det_barcode_62",
			"test_det_barcode_63", "test_det_barcode_64", "test_det_barcode_65", "test_det_barcode_66",
			"test_det_barcode_67", "test_det_barcode_68", "test_det_barcode_69", "test_det_barcode_70",
			"test_det_barcode_71", "test_det_barcode_72", "test_det_barcode_73", "test_det_barcode_74",
			"test_det_barcode_75", "test_det_barcode_76", "test_det_barcode_77", "test_det_barcode_78",
			"test_det_barcode_79", "test_det_barcode_80", "test_det_barcode_81", "test_det_barcode_82",
			"test_det_barcode_83", "test_det_barcode_84", "test_det_barcode_85", "test_det_barcode_86",
			"test_det_barcode_87", "test_det_barcode_88", "test_det_barcode_89", "test_det_barcode_90",
			"test_det_barcode_91", "test_det_barcode_92", "test_det_barcode_93", "test_det_barcode_94",
			"test_det_barcode_95", "test_det_barcode_96" };

	public static String[] rnaResultFields = new String[] { "covid_rna_results1", "covid_rna_results2",
			"covid_rna_results3", "covid_rna_results4", "covid_rna_results5", "covid_rna_results6",
			"covid_rna_results7", "covid_rna_results8", "covid_rna_results9", "covid_rna_results10",
			"covid_rna_results11", "covid_rna_results12", "covid_rna_results13", "covid_rna_results14",
			"covid_rna_results15", "covid_rna_results16", "covid_rna_results17", "covid_rna_results18",
			"covid_rna_results19", "covid_rna_results20", "covid_rna_results21", "covid_rna_results22",
			"covid_rna_results23", "covid_rna_results24", "covid_rna_results25", "covid_rna_results26",
			"covid_rna_results27", "covid_rna_results28", "covid_rna_results29", "covid_rna_results30",
			"covid_rna_results31", "covid_rna_results32", "covid_rna_results33", "covid_rna_results34",
			"covid_rna_results35", "covid_rna_results36", "covid_rna_results37", "covid_rna_results38",
			"covid_rna_results39", "covid_rna_results40", "covid_rna_results41", "covid_rna_results42",
			"covid_rna_results43", "covid_rna_results44", "covid_rna_results45", "covid_rna_results46",
			"covid_rna_results47", "covid_rna_results48", "covid_rna_results49", "covid_rna_results50",
			"covid_rna_results51", "covid_rna_results52", "covid_rna_results53", "covid_rna_results54",
			"covid_rna_results55", "covid_rna_results56", "covid_rna_results57", "covid_rna_results58",
			"covid_rna_results59", "covid_rna_results60", "covid_rna_results61", "covid_rna_results62",
			"covid_rna_results63", "covid_rna_results64", "covid_rna_results65", "covid_rna_results66",
			"covid_rna_results67", "covid_rna_results68", "covid_rna_results69", "covid_rna_results70",
			"covid_rna_results71", "covid_rna_results72", "covid_rna_results73", "covid_rna_results74",
			"covid_rna_results75", "covid_rna_results76", "covid_rna_results77", "covid_rna_results78",
			"covid_rna_results79", "covid_rna_results80", "covid_rna_results81", "covid_rna_results82",
			"covid_rna_results83", "covid_rna_results84", "covid_rna_results85", "covid_rna_results86",
			"covid_rna_results87", "covid_rna_results88", "covid_rna_results89", "covid_rna_results90",
			"covid_rna_results91", "covid_rna_results92", "covid_rna_results93", "covid_rna_results94",
			"covid_rna_results95", "covid_rna_results96" };

	public static String[] assayResultFields = new String[] { "test_assay_result_1", "test_assay_result_2",
			"test_assay_result_3", "test_assay_result_4", "test_assay_result_5", "test_assay_result_6",
			"test_assay_result_7", "test_assay_result_8", "test_assay_result_9", "test_assay_result_10",
			"test_assay_result_11", "test_assay_result_12", "test_assay_result_13", "test_assay_result_14",
			"test_assay_result_15", "test_assay_result_16", "test_assay_result_17", "test_assay_result_18",
			"test_assay_result_19", "test_assay_result_20", "test_assay_result_21", "test_assay_result_22",
			"test_assay_result_23", "test_assay_result_24", "test_assay_result_25", "test_assay_result_26",
			"test_assay_result_27", "test_assay_result_28", "test_assay_result_29", "test_assay_result_30",
			"test_assay_result_31", "test_assay_result_32", "test_assay_result_33", "test_assay_result_34",
			"test_assay_result_35", "test_assay_result_36", "test_assay_result_37", "test_assay_result_38",
			"test_assay_result_39", "test_assay_result_40", "test_assay_result_41", "test_assay_result_42",
			"test_assay_result_43", "test_assay_result_44", "test_assay_result_45", "test_assay_result_46",
			"test_assay_result_47", "test_assay_result_48", "test_assay_result_49", "test_assay_result_50",
			"test_assay_result_51", "test_assay_result_52", "test_assay_result_53", "test_assay_result_54",
			"test_assay_result_55", "test_assay_result_56", "test_assay_result_57", "test_assay_result_58",
			"test_assay_result_59", "test_assay_result_60", "test_assay_result_61", "test_assay_result_62",
			"test_assay_result_63", "test_assay_result_64", "test_assay_result_65", "test_assay_result_66",
			"test_assay_result_67", "test_assay_result_68", "test_assay_result_69", "test_assay_result_70",
			"test_assay_result_71", "test_assay_result_72", "test_assay_result_73", "test_assay_result_74",
			"test_assay_result_75", "test_assay_result_76", "test_assay_result_77", "test_assay_result_78",
			"test_assay_result_79", "test_assay_result_80", "test_assay_result_81", "test_assay_result_82",
			"test_assay_result_83", "test_assay_result_84", "test_assay_result_85", "test_assay_result_86",
			"test_assay_result_87", "test_assay_result_88", "test_assay_result_89", "test_assay_result_90",
			"test_assay_result_91", "test_assay_result_92", "test_assay_result_93", "test_assay_result_94",
			"test_assay_result_95", "test_assay_result_96" };

	public static String[] extractionBarcodes = new String[] { "test_verify_result_1", "test_verify_result_2",
			"test_verify_result_3", "test_verify_result_4", "test_verify_result_5", "test_verify_result_6",
			"test_verify_result_7", "test_verify_result_8", "test_verify_result_9", "test_verify_result_10",
			"test_verify_result_11", "test_verify_result_12", "test_verify_result_13", "test_verify_result_14",
			"test_verify_result_15", "test_verify_result_16", "test_verify_result_17", "test_verify_result_18",
			"test_verify_result_19", "test_verify_result_20", "test_verify_result_21", "test_verify_result_22",
			"test_verify_result_23", "test_verify_result_24", "test_verify_result_25", "test_verify_result_26",
			"test_verify_result_27", "test_verify_result_28", "test_verify_result_29", "test_verify_result_30",
			"test_verify_result_31", "test_verify_result_32", "test_verify_result_33", "test_verify_result_34",
			"test_verify_result_35", "test_verify_result_36", "test_verify_result_37", "test_verify_result_38",
			"test_verify_result_39", "test_verify_result_40", "test_verify_result_41", "test_verify_result_42",
			"test_verify_result_43", "test_verify_result_44", "test_verify_result_45", "test_verify_result_46",
			"test_verify_result_47", "test_verify_result_48", "test_verify_result_49", "test_verify_result_50",
			"test_verify_result_51", "test_verify_result_52", "test_verify_result_53", "test_verify_result_54",
			"test_verify_result_55", "test_verify_result_56", "test_verify_result_57", "test_verify_result_58",
			"test_verify_result_59", "test_verify_result_60", "test_verify_result_61", "test_verify_result_62",
			"test_verify_result_63", "test_verify_result_64", "test_verify_result_65", "test_verify_result_66",
			"test_verify_result_67", "test_verify_result_68", "test_verify_result_69", "test_verify_result_70",
			"test_verify_result_71", "test_verify_result_72", "test_verify_result_73", "test_verify_result_74",
			"test_verify_result_75", "test_verify_result_76", "test_verify_result_77", "test_verify_result_78",
			"test_verify_result_79", "test_verify_result_80", "test_verify_result_81", "test_verify_result_82",
			"test_verify_result_83", "test_verify_result_84", "test_verify_result_85", "test_verify_result_86",
			"test_verify_result_87", "test_verify_result_88", "test_verify_result_89", "test_verify_result_90",
			"test_verify_result_91", "test_verify_result_92", "test_verify_result_93", "test_verify_result_94",
			"test_verify_result_95", "test_verify_result_96" };
}
