// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 08/05/2020 17:09:52+0200.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.ub.ehealth.dhislink.instrument;

import bw.ub.ehealth.dhislink.instrument.vo.InstrumentVO;
import org.springframework.stereotype.Repository;

/**
 * @see Instrument
 */
@Repository("instrumentDao")
public class InstrumentDaoImpl
    extends InstrumentDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    public void toInstrumentVO(
        Instrument source,
        InstrumentVO target)
    {
        // TODO verify behavior of toInstrumentVO
        super.toInstrumentVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrumentVO toInstrumentVO(final Instrument entity)
    {
        // TODO verify behavior of toInstrumentVO
        return super.toInstrumentVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Instrument loadInstrumentFromInstrumentVO(InstrumentVO instrumentVO)
    {
        // TODO implement loadInstrumentFromInstrumentVO
        throw new UnsupportedOperationException("bw.ub.ehealth.dhislink.instrument.loadInstrumentFromInstrumentVO(InstrumentVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (instrumentVO.getId() == null)
        {
            return  Instrument.Factory.newInstance();
        }
        else
        {
            return this.load(instrumentVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public Instrument instrumentVOToEntity(InstrumentVO instrumentVO)
    {
        // TODO verify behavior of instrumentVOToEntity
        Instrument entity = this.loadInstrumentFromInstrumentVO(instrumentVO);
        this.instrumentVOToEntity(instrumentVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void instrumentVOToEntity(
        InstrumentVO source,
        Instrument target,
        boolean copyIfNull)
    {
        // TODO verify behavior of instrumentVOToEntity
        super.instrumentVOToEntity(source, target, copyIfNull);
    }
}